/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void shopStringTest() {
        Shop test = new Shop("Pop","This is a really good restaurant!",5);
        System.out.println(test.toString());
        assertEquals("Name: Pop,Description: This is a really good restaurant!,Price: 5,Reviews: 0", test.toString());

    }
    @Test void reviewTest(){
        Review test = new Review("Adam", "", 5);
        System.out.println(test.toString());
        assertEquals("Name: Adam,Description: Happy,Rating: 5.",test.toString());
    }
    @Test void theaterAddTest(){
        Theater test = new Theater("MarkWorld");
        test.addMovie("The GodFather");
        test.addMovie("The GodFather2");
        test.addMovie("The GodFather3");
        System.out.println(test.movies);
//        assertEquals("Name of Theater: , MarkWorldMovies: , The GodFather.",test.toString());
    }
    @Test void theaterRemoveTest(){
        Theater test = new Theater("MarkWorld");
        test.addMovie("The GodFather");
        test.addMovie("The GodFather2");
        test.removeMovie("The GodFather");
        System.out.println(test.movies);
//        assertEquals("Name of Theater: , MarkWorldMovies: , The GodFather.",test.toString());
        assertEquals("[The GodFather2]",test.movies.toString());
    }
}

